spring:
# Spring boot가 기본적으로 메모리 DB를 사용하여 테스트를 검증해주므로 아래 주석처리한 설정도 필요없게 된다.

#  datasource:
##    url: jdbc:h2:tcp://localhost/~/Desktop/sd-projects/db/h2 # RDB 사용
#    url: jdbc:h2:mem:test # 메모리 사용
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create # Spring boot는 "create-drop"으로 실행한다.
#    properties:
#      hibernate:
##        show_sql: true
#        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug